### ISSUE TITLE
lotteries.yml Completely wiped after server restart

### ISSUE THREAD

**Issue by maroselis** [Randude14/LotteryPlus#20]
Config (mostly default):
http://pastebin.com/Cd6ZkXsV
Lotteries.yml (Was completely wiped upon restart of server but looked similar to):
http://pastebin.com/eWY4rag5

Spigot version: 1.5.2 R0.1 - 837
Lotteries Plus Version: v0.8.8a

I had Lottery+ running for about 3 days, everyone bought tickets etc. Pot kept going up, all was well. I restarted my server today and found out that my entire lotteries.yml file was wiped. I did everything precisely as described in the Tutorial (creating lotteries through console), and it still wiped itself.

Other than that, Lottery+ was working perfectly until it got wiped.

Is there a way to add something so that if the file cannot be read properly, then it creates a backup of it? (Similar to how Essentials config creates backups) 

Or is this a common issue and there's a simple fix to preventing it?

Thanks for any and all information you may be able to share.

**Comment by MarvinTM111** [comment]
Same here using Bukkit 1.11.2-R0.1 L+ v 1.0.1

**Comment by Randude14** [comment]
Did anything happen before hand when you closed the server before starting it up again?

**Comment by MarvinTM111** [comment]
See issue A few errors #37
