### ISSUE TITLE
A few errors

### ISSUE THREAD

**Issue by MarvinTM111** [Randude14/LotteryPlus#37]
When installing 1.0.1 server would not load said Is version up to date? So I loaded v1.0 and then after it generated all the files replaced it with 1.0.1. Now errors while trying to open GUI.

21.05 10:29:48 [Server] WARN at java.lang.Thread.run(Unknown Source)
21.05 10:29:48 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
21.05 10:29:48 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
21.05 10:29:48 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:361)
21.05 10:29:48 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:397)
21.05 10:29:48 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:615)
21.05 10:29:48 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:629)
21.05 10:29:48 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
21.05 10:29:48 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
21.05 10:29:48 [Server] WARN at com.randude14.lotteryplus.command.CommandManager.onCommand(CommandManager.java:57)
21.05 10:29:48 [Server] WARN at com.randude14.lotteryplus.command.GuiCreatorCommand.execute(GuiCreatorCommand.java:17)
21.05 10:29:48 [Server] WARN at com.randude14.lotteryplus.LotteryPlus.openGui(LotteryPlus.java:207)
21.05 10:29:48 [Server] WARN at com.randude14.lotteryplus.gui.MainFrame.<init>(MainFrame.java:39)
21.05 10:29:48 [Server] WARN at javax.swing.JFrame.<init>(Unknown Source)
21.05 10:29:48 [Server] WARN at java.awt.Frame.<init>(Unknown Source)
21.05 10:29:48 [Server] WARN at java.awt.Frame.<init>(Unknown Source)
21.05 10:29:48 [Server] WARN at java.awt.Window.<init>(Unknown Source)
21.05 10:29:48 [Server] WARN at java.awt.GraphicsEnvironment.checkHeadless(Unknown Source)
21.05 10:29:48 [Server] INFO No X11 DISPLAY variable was set, but this program performed an operation which requires it.
21.05 10:29:48 [Server] WARN java.awt.HeadlessException: 
21.05 10:29:48 [Server] INFO - Exception caught while executing this command.

[config.txt](https://github.com/Randude14/LotteryPlus/files/1017083/config.txt)
[lotteries.txt](https://github.com/Randude14/LotteryPlus/files/1017084/lotteries.txt)

**Comment by Randude14** [comment]
Are you running the server on a linux terminal or some other space where there is no graphical environment and as far as I'm concerned there is no way to do it in code. It all depends on your system sorry. As far as the lotteries.yml clearing, I'm trying to look at the issue now.

**Comment by Randude14** [comment]
Is there nothing more you can provide about the lotteries.yml resetting, any errors or weird messages other than the "Is this version up todate?" Thanks.
